#!/bin/bash
# Generates key and certificate
set -e
mkdir -p "$(dirname "$0")"
openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  -keyout "$(dirname "$0")/selfsigned.key" \
  -out "$(dirname "$0")/selfsigned.crt" \
  -subj "/CN=localhost"
chmod 600 "$(dirname "$0")/selfsigned.key"